# Generated by Django 4.2.16 on 2025-04-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Encargado',
            new_name='Administrador',
        ),
        migrations.AlterModelOptions(
            name='administrador',
            options={'ordering': ['nombre'], 'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
    ]
