# Generated by Django 4.2.16 on 2025-04-10 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Modulo_admin', '0004_areas_deleted_at_areas_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
