# Generated by Django 4.2.16 on 2025-04-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0006_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=50)),
                ('apoderado_titular', models.CharField(max_length=255)),
                ('apoderado_suplente', models.CharField(blank=True, max_length=255, null=True)),
                ('familiar_1', models.CharField(blank=True, max_length=255, null=True)),
                ('familiar_1_relacion', models.CharField(blank=True, max_length=100, null=True)),
                ('familiar_1_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('familiar_2', models.CharField(blank=True, max_length=255, null=True)),
                ('familiar_2_relacion', models.CharField(blank=True, max_length=100, null=True)),
                ('familiar_2_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['curso', 'nombre'],
            },
        ),
    ]
