# Generated by Django 4.2.16 on 2025-04-16 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0006_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un RUT válido en formato XX.XXX.XXX-X', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]$')], verbose_name='RUT')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido. Debe contener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de Teléfono')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('cursos', models.ManyToManyField(related_name='inspectores', to='Modulo_admin.curso', verbose_name='Cursos a cargo')),
            ],
            options={
                'verbose_name': 'Inspector',
                'verbose_name_plural': 'Inspectores',
                'ordering': ['nombre'],
            },
        ),
    ]
