# Generated by Django 4.2.16 on 2025-04-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0007_alumno'),
        ('Modulo_admin', '0007_inspector'),
    ]

    operations = [
    ]
