# Generated by Django 4.2.16 on 2025-04-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0008_merge_0007_alumno_0007_inspector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nivel', 'nombre'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('Pre-basica', 'Pre-básica'), ('Basica', 'Básica'), ('Media', 'Media')], default='Basica', max_length=20, verbose_name='Nivel Educativo'),
        ),
    ]
