# Generated by Django 4.2.16 on 2025-04-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0008_merge_0007_alumno_0007_inspector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='activo',
        ),
    ]
