# Generated by Django 4.2.16 on 2025-04-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0009_alter_curso_options_curso_nivel'),
        ('Modulo_admin', '0009_remove_alumno_activo'),
    ]

    operations = [
    ]
