# Generated by Django 4.2.16 on 2025-04-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0011_alter_alumno_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='rut_apoderadoS',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='rut_apoderadoT',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='rut_falimilar_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='rut_familiar_1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
