# Generated by Django 4.2.16 on 2025-04-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0012_alumno_rut_apoderados_alumno_rut_apoderadot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='rut_falimilar_2',
            new_name='rut_familiar_2',
        ),
    ]
