# Generated by Django 4.2.16 on 2025-04-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0010_merge_20250416_1127'),
        ('Modulo_admin', '0013_rename_rut_falimilar_2_alumno_rut_familiar_2'),
    ]

    operations = [
    ]
