# Generated by Django 4.2.16 on 2025-04-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0015_alumno_numero_apoderados_alumno_numero_apoderadot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='numero_apoderadoS',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='numero_apoderadoT',
        ),
    ]
