# Generated by Django 4.2.16 on 2025-04-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0016_remove_alumno_numero_apoderados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='telefono_apoderadoS',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Apoderado Suplente'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono_apoderadoT',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Apoderado Titular'),
        ),
    ]
