# Generated by Django 4.2.16 on 2025-04-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0017_alumno_telefono_apoderados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoEgresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('ultimo_curso', models.CharField(max_length=50)),
                ('apoderado_titular', models.CharField(max_length=255)),
                ('rut_apoderadoT', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono_apoderadoT', models.CharField(blank=True, max_length=20, null=True)),
                ('apoderado_suplente', models.CharField(blank=True, max_length=255, null=True)),
                ('rut_apoderadoS', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono_apoderadoS', models.CharField(blank=True, max_length=20, null=True)),
                ('familiar_1', models.CharField(blank=True, max_length=255, null=True)),
                ('familiar_1_relacion', models.CharField(blank=True, max_length=100, null=True)),
                ('familiar_1_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rut_familiar_1', models.CharField(blank=True, max_length=15, null=True)),
                ('familiar_2', models.CharField(blank=True, max_length=255, null=True)),
                ('familiar_2_relacion', models.CharField(blank=True, max_length=100, null=True)),
                ('familiar_2_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rut_familiar_2', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_egreso', models.DateField(auto_now_add=True)),
                ('año_egreso', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Alumno Egresado',
                'verbose_name_plural': 'Alumnos Egresados',
                'ordering': ['-año_egreso', 'nombre'],
            },
        ),
    ]
