# Generated by Django 4.2.16 on 2025-04-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0018_alumnoegresado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='tum_tum',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
