# Generated by Django 4.2.16 on 2025-04-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0019_alumno_tum_tum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='tum_tum',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
