# Generated by Django 4.2.16 on 2025-04-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0020_remove_alumno_tum_tum_alter_alumno_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='is_salida',
            field=models.BooleanField(default=False, verbose_name='Inspector de Salida'),
        ),
    ]
