# Generated by Django 4.2.16 on 2025-04-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0021_inspector_is_active_inspector_is_salida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='is_salida',
        ),
    ]
