# Generated by Django 4.2.16 on 2025-04-01 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_registro', models.CharField(editable=False, max_length=4, unique=True)),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=255)),
                ('autorizado_por', models.CharField(max_length=255)),
                ('motivo_salida', models.TextField()),
                ('hora_salida', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_regreso', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
