# Generated by Django 4.2.16 on 2025-04-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModuloFuncionario',
            new_name='RegistroSalida',
        ),
    ]
