# Generated by Django 4.2.16 on 2025-04-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_funcionarios', '0002_rename_modulofuncionario_registrosalida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosalida',
            name='motivo_salida',
            field=models.CharField(choices=[('Tramites', 'Trámites'), ('Compras', 'Compras'), ('Salidas Pedagogicas', 'Salidas Pedagógicas'), ('Otros', 'Otros')], max_length=20),
        ),
    ]
