# Generated by Django 4.2.16 on 2025-04-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_funcionarios', '0003_alter_registrosalida_motivo_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosalida',
            name='area_perteneciente',
            field=models.CharField(choices=[('Administracion', 'Administración'), ('Docencia', 'Docencia'), ('Auxiliar', 'Auxiliar'), ('Otra', 'Otra')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
