# Generated by Django 4.2.16 on 2025-04-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_admin', '0003_areas'),
        ('Modulo_funcionarios', '0004_registrosalida_area_perteneciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosalida',
            name='area_perteneciente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registrosalida',
            name='autorizado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='Modulo_admin.areas'),
        ),
    ]
