# Generated by Django 4.2.16 on 2025-04-04 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_funcionarios', '0006_alter_registrosalida_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosalida',
            name='rut',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Ingrese un RUT válido en formato XX.XXX.XXX-X', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]$')], verbose_name='RUT'),
        ),
    ]
