# Generated by Django 4.2.16 on 2025-04-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_funcionarios', '0007_alter_registrosalida_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosalida',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
