# Generated by Django 4.2.16 on 2025-04-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_funcionarios', '0009_alter_registrosalida_autorizado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosalida',
            name='codigo_registro',
            field=models.CharField(editable=False, max_length=5, unique=True),
        ),
    ]
