# Generated by Django 4.2.16 on 2025-04-15 20:53

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_persona_retira', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Ingrese un RUT válido en formato XX.XXX.XXX-X', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]$')], verbose_name='RUT de quien retira')),
                ('tipo_persona', models.CharField(choices=[('Apoderado', 'Apoderado'), ('Apoderado Suplente', 'Apoderado Suplente'), ('Otro', 'Otro')], max_length=20, verbose_name='Relación con el estudiante')),
                ('rut_estudiante', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Ingrese un RUT válido en formato XX.XXX.XXX-X', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]$')], verbose_name='RUT del estudiante')),
                ('nombre_estudiante', models.CharField(max_length=255, verbose_name='Nombre del estudiante')),
                ('curso', models.CharField(max_length=20, verbose_name='Curso')),
                ('inspector_cargo', models.CharField(max_length=255, verbose_name='Inspector a cargo')),
                ('motivo_retiro', models.CharField(choices=[('Asuntos Medicos', 'Asuntos Médicos'), ('Asuntos Familiares', 'Asuntos Familiares'), ('Motivos Personales', 'Motivos Personales'), ('Prefiero no decirlo', 'Prefiero no decirlo')], max_length=20, verbose_name='Motivo del retiro')),
                ('hora_retiro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del retiro')),
            ],
        ),
    ]
