# Generated by Django 4.2.16 on 2025-04-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_alumnos', '0002_remove_registroretiro_tipo_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroretiro',
            name='nombre_persona_retira',
            field=models.CharField(default=1, max_length=255, verbose_name='Nombre de quien retira'),
            preserve_default=False,
        ),
    ]
