# Generated by Django 4.2.16 on 2025-04-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_alumnos', '0006_alter_registroretiro_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroretiro',
            name='estado',
            field=models.CharField(choices=[('waiting', 'En Espera'), ('confirmed', 'Confirmado'), ('rejected', 'Rechazado'), ('timeout', 'Tiempo de espera agotado')], default='waiting', max_length=20),
        ),
    ]
