# Generated by Django 4.2.16 on 2025-04-30 20:48

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_alumnos', '0007_alter_registroretiro_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroJustificativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_persona_justifica', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Ingrese un RUT válido en formato XX.XXX.XXX-X', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]$')], verbose_name='RUT de quien justifica')),
                ('nombre_persona_justifica', models.CharField(max_length=255, verbose_name='Nombre de quien justifica')),
                ('rut_estudiante', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Ingrese un RUT válido en formato XX.XXX.XXX-X', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]$')], verbose_name='RUT del estudiante')),
                ('nombre_estudiante', models.CharField(max_length=255, verbose_name='Nombre del estudiante')),
                ('curso', models.CharField(max_length=20, verbose_name='Curso')),
                ('hora_llegada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de llegada')),
                ('tipo_justificacion', models.CharField(choices=[('con_certificado', 'Con Certificado Médico'), ('sin_certificado', 'Sin Certificado Médico')], max_length=20, verbose_name='Tipo de justificación')),
                ('codigo_verificacion', models.CharField(blank=True, max_length=5, null=True, verbose_name='Codigo de verificación')),
            ],
        ),
    ]
