# Generated by Django 4.2.16 on 2025-05-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_alumnos', '0008_registrojustificativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrojustificativo',
            name='motivo_justificacion',
            field=models.CharField(blank=True, choices=[('Asuntos Medicos', 'Asuntos Médicos'), ('Asuntos Familiares', 'Asuntos Familiares'), ('Tramites', 'Tramites'), ('Otro', 'Otro')], max_length=20, null=True, verbose_name='Motivo de la justificación'),
        ),
    ]
